### ISSUE TITLE
It would be proper to respect decency

### ISSUE THREAD

**Issue by bsrginru** [BabyDragonPRO/BDPHud#1]
I suggest you keep the authorship of the source codes you copied.
Or should I contact github support? (abuse)

Remind: [https://github.com/bsrginru/informator](https://github.com/bsrginru/informator)

**Comment by BabyDragonPRO** [comment]
Do you meen that i need to write in credits that some methods in my code was bring from informator?
Because i did't copied it, I saw how you did some things with which I had problems so made same solution.
So if you want i can write that some solutions was brought from your code.
