### ISSUE TITLE
Issue on the latest version of Forge ModLoader

### ISSUE THREAD

**Issue by QMan0** [BabyDragonPRO/BDPHud#2]
On the latest version of Minecraft Forge (28.0.45) mod has a issue:
BabyDragonPRO's Hud (bdphud) has failed to load correctly net/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent
[latest.log](https://github.com/BabyDragonPRO/BDPHud/files/3477544/latest.log)

**Comment by BabyDragonPRO** [comment]
Yes I know about it.
I fixed this issue in my new beta version of mod, but this version have some bugs(I'm making light overlay).
I will publish release version yesterday.
