### ISSUE TITLE
Not working settings and minor issue.

### ISSUE THREAD

**Issue by QMan0** [BabyDragonPRO/BDPHud#3]
Some settings don't save and update values properly:

Mob Info:
- Opacity
- View Distance,

Items Info:
- Opacity,

Light Overlay:
- XZ Range
- Y Range,

Block Info:
- Opacity
- View Distance,

Time Info:
- Opacity,

Speed Info:
- Opacity.

Minor Issue: Sometimes Block Info after disabling and enabling doesn't work without enabled Mob Info.

**Comment by BabyDragonPRO** [comment]
About sliders(all mentioned properties is sliders): it's not saving setting if you release mouse button out side slider bounds.(I'm fixing it)

About minor issue: I will test it, and try to fix.

**Comment by BabyDragonPRO** [comment]
fixed in 0.9.4
https://github.com/BabyDragonPRO/BDPHud/releases/tag/0.9.4
