### ISSUE TITLE
Block Info text issue with disabled icon

### ISSUE THREAD

**Issue by QMan0** [BabyDragonPRO/BDPHud#4]
Disabling the icon for the Block Info function causes a problem with the text position.
![First](https://user-images.githubusercontent.com/53868746/62838694-32cfad00-bc99-11e9-916f-71ec69a25c01.png)
![Second](https://user-images.githubusercontent.com/53868746/62838699-3c591500-bc99-11e9-8dcd-6108fea166f3.png)

**Comment by BabyDragonPRO** [comment]
I will fix it, but not earlier then 25.08.

**Comment by BabyDragonPRO** [comment]
Fixed in 1.0.0
